### ISSUE TITLE
load with requireJS

### ISSUE THREAD

**Issue by hzozimo** [bumbeishvili/org-chart#130] opened 2022-03-14 17:31 UTC
I am trying to load orgChart with requireJS for a project. But I am having problems.

The project give acess to the HTML only trough javascript, so I cant load a script tag.

I did that way:

(paint is the method called to plot the view in the HTML)

```
define(["jquery",
 "./lib/js/d3.min", 
 "./lib/js/d3-org-chart", 
"./lib/js/d3-flextree"
], function ($,
  d3,
  orgChart,
  flextree
     ) {
  "use strict";

  return {
    paint: function ($element, layout) {
      // make sure HTML is empty
      $element.empty();

      // Create DOM where the timeline will be rendered
      const visualization = $("<div/>").addClass("chart-container");
      $element.append(visualization);

      console.log(d3);
    },
  };
});


```

If I load just d3, the console.log(d3) shows the lib objects and funcions, but when I load orgChart and flextree, or just orgChart, this message shows is the console

```
d3-selection.js:1 Uncaught SyntaxError: Unexpected token '<'
d3-array.js:1 Uncaught SyntaxError: Unexpected token '<'
d3-hierarchy.js:1 Uncaught SyntaxError: Unexpected token '<'
d3-zoom.js:1 Uncaught SyntaxError: Unexpected token '<'
d3-flextree.js:1 Uncaught SyntaxError: Unexpected token '<'
d3-shape.js:1 Uncaught SyntaxError: Unexpected token '<'
setup-view.5a522120bca98fc56f6c.js:9 TypeError: Cannot read property 'selection' of undefined
    at Object.<anonymous> (d3-org-chart.js:29)
    at Object.execCb (requirejs.0680423abfb19dc502f8.js:9)
    at r.check (requirejs.0680423abfb19dc502f8.js:9)
    at r.<anonymous> (requirejs.0680423abfb19dc502f8.js:9)
    at requirejs.0680423abfb19dc502f8.js:9
    at requirejs.0680423abfb19dc502f8.js:9
    at each (requirejs.0680423abfb19dc502f8.js:9)
    at r.emit (requirejs.0680423abfb19dc502f8.js:9)
    at r.check (requirejs.0680423abfb19dc502f8.js:9)
    at r.enable (requirejs.0680423abfb19dc502f8.js:9)
```

Can anyone help me doing this? Thanks

**Comment by bumbeishvili** [comment] 2023-09-16 08:42
@hzozimo  if you can provide online sample where the issue is reproduced I can take a look, otherwise, I have to close it since don't know what's happening just looking at the snippet

**Closed** 2023-09-16 08:43 UTC
Labels: Possible Bug
