### ISSUE TITLE
Chart sometimes changes zoom level on node expand

### ISSUE THREAD

**Issue by NordicLight** [bumbeishvili/org-chart#122] opened 2022-02-10 14:21 UTC
**Describe the bug**
When expanding a node sometimes the chart zooms out (the nodes gets larger) or zooms in (the nodes get smaller)

The feeling is that it is happens only when there are few nodes. Also if the user has pressed any of the zoom button once we never see this behaviour.  Unfortunately we cannot reproduce it consistently but if we add fit to the render e.g. render().fit() we see the same large nodes on first draw.

Is there a way to force the chart to not change zoom size on render()?

**Expected behavior**
The zoom level should never change expanding/collapsing nodes

**Desktop (please complete the following information):**
- Chrome

**Comment by bumbeishvili** [comment] 2022-02-10 14:34
@NordicLight 

Can you prepare an example or at least a recording where this issue will be reproduced? I can't reproduce it

**Comment by NordicLight** [comment] 2022-02-10 15:23
Thank you for the quick response! 

I do not have a good way to reproduce it myself. It can happen directly or as in the recording below after 40 seconds of trying to reproduce it. 

It has something to do with your auto fitting of the chart you are doing in the background. Would be great if there i an option .nofitting().render() or nozoom.render(). I can also mention that we are updating the chart by directly modifying the nodes to keep expand/collapse state. But I think we have seen it directly on first zoom as well.

https://user-images.githubusercontent.com/9700899/153438425-190fcb51-770a-445e-bbbd-deeec925032a.mp4

**Comment by bumbeishvili** [comment] 2022-02-10 16:25
As I see initially chart is zoomed out, can you let me know how you did it?

**Comment by bumbeishvili** [comment] 2022-02-10 23:23
It's an issue indeed, currently I am packed with the projects and I doubt that I will have a time for it, but will jump to it at earliest convenience

**Comment by bumbeishvili** [comment] 2023-09-16 08:27
@NordicLight I had another look but it seems hard to understand what's happening without seeing an online sample where the issue is reproduced. I'll close this issue and will reopen if reproduced sample will be commented

**Closed by bumbeishvili** 2023-09-16 08:27 UTC
Labels: Possible Bug, can't reproduce, v3 plan
