### ISSUE TITLE
Wrong elements order

### ISSUE THREAD

**Issue by evansmith1377** [bumbeishvili/org-chart#34] opened 2020-09-30 16:28 UTC
This functions well in the reference implementations, and it initially worked in my implementation, but it is not currently behaving well for me. This leads me to believe I have borked my implementation in some way - maybe because I'm re-rendering the chart on data changes. Please advise if you know of a way to fix my usage. Details of my problem:

- Incorrect order:
![image](https://user-images.githubusercontent.com/26821065/94711749-262f6d80-030e-11eb-9881-9c0891cc3409.png)
Gives the image behind the template:
![image](https://user-images.githubusercontent.com/26821065/94712225-cc7b7300-030e-11eb-829e-67233c9bd42b.png)

- Correct order:
![image](https://user-images.githubusercontent.com/26821065/94711543-dc468780-030d-11eb-9280-067d29d37c63.png)
Gives the image in front of the template:
![image](https://user-images.githubusercontent.com/26821065/94712265-db622580-030e-11eb-8a26-21788ef776c7.png)

I think the fix is to move the `// Add background rectangle for node image` code down a few lines so it is after the `// Add foreignObject element inside rectangle` code. That seems to fix it locally for me. However, even with current code order, I see that the DOM elements render in the correct order in the [reference implementations](https://observablehq.com/@bumbeishvili/d3-v5-organization-chart). I'm interested in any unintended side effects this may introduce. Image may be rendered before template for good reason.

Please forgive my general lack of knowledge if I'm misinterpreting something basic. I'm very new to web development. Thanks for an awesome org chart!

**Comment by bumbeishvili** [comment] 2020-09-30 20:15
I think you are right

There is not any intended behavior behind that order, so either of them will work. I just did not think about a possible problem, since it worked for me without problems (I was also rerendering it)

I will keep this open and once I will have time, I will take a closer look. I think in the end I'll follow your suggestion

**Comment by bumbeishvili** [comment] 2021-07-17 20:36
In the new version 2 `node-image-group` will be removed completely and instead node content will take care of it, you will be able to use normal HTML for images

https://github.com/bumbeishvili/d3-organization-chart/blob/b64f9ef60f9eeff48969df2ecead9a5504c501f3/src/d3-org-chart.js#L773

**Comment by bumbeishvili** [comment] 2021-08-14 18:17
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)

**Closed by bumbeishvili** 2021-08-14 18:17 UTC
Labels: bug, Fixed in dev
