### ISSUE TITLE
OrgChart not truly updating with prop change

### ISSUE THREAD

**Issue by CocoYubari** [bumbeishvili/org-chart#144] opened 2022-05-03 13:29 UTC
First of all, thank you for the effort you put into designing this library.

I am currently using this library with the React integration, generating the HTML string of each nodeContent using ReactDOMServer.renderToString() on a node component I created myself. 

The goal is to be able to hide the pictures on the node by passing a property to OrgChartComponent and then to the node itself. 

While when I click the associated checkbox the pictures are effectively hidden, the moment I try to expand/collapse a node via library button, the app seems to load the previous chart, despite useLayoutEffect() being triggered by the change of that property. 
It loads the correct nodeContent only after a couple of triggers of onNodeClick(), which also updates props.data.

I tried to generate a new OrgChart with each useLayoutEffect(), but it has proven ineffective

Is there any way I can get the library buttons to sync to the correct chart right away?

**Comment by CocoYubari** [comment] 2022-05-03 15:31
I am unable to provide the code I am working on, but this zip contains a video with the behaviour I am referring to (github did not allow me to load the video directly).
As you can see, as the property changes to false, a download button outside the OrgChart activates, but when I click on the library button, the pictures are shown despite the property being set to false. 

[VID_issue.zip](https://github.com/bumbeishvili/org-chart/files/8611578/VID_issue.zip)

**Comment by CocoYubari** [comment] 2022-05-24 08:28
I've found another possible fix: one can also set a key to force it to redraw entirely

**Comment by bumbeishvili** [comment] 2022-05-24 08:30
> I've found another possible fix: one can also set a key to force it to redraw entirely

What do you mean exactly? Can you elaborate?

**Comment by CocoYubari** [comment] 2022-05-24 10:10
> > I've found another possible fix: one can also set a key to force it to redraw entirely
> 
> What do you mean exactly? Can you elaborate?

I mean inside the file OrgChart.js, when I return the OrgChartComponent

`<OrgChartComponent 
                key={/*insert property in string format here*/}
                setClick={click => (addNodeChildFunc = click)}
                onNodeClick={onNodeClick}
                data={data}
            />`

**Comment by bumbeishvili** [comment] 2023-09-16 08:59
I had another look. This behavior usually happens when invoking `new OrgChart()` on the same container multiple times. Instead, this should happen once and subsequent updates should happen via `chart.data()...` methods.

I can look into online sample where issue is reproduced, otherwise have to close it since I won't be able to make any progress in it

**Closed by bumbeishvili** 2023-09-16 08:59 UTC
Labels: Possible Bug
